services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic telemetry.sensors.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic telemetry.snapshots.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic telemetry.hubs.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true

  warehouse-db:
    image: postgres:16-alpine
    container_name: warehouse-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse

    ports:
      - "5435:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U warehouse -d warehouse" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - warehouse-db-data:/var/lib/postgresql/data

  shopping-cart-db:
    image: postgres:16-alpine
    container_name: shopping-cart-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: shopping_cart
      POSTGRES_USER: shopping_cart
      POSTGRES_PASSWORD: shopping_cart

    ports:
      - "5434:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shopping_cart -d shopping_cart" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - shopping-cart-db-data:/var/lib/postgresql/data

  shopping-store-db:
    image: postgres:16-alpine
    container_name: shopping-store-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: shopping_store
      POSTGRES_USER: shopping_store
      POSTGRES_PASSWORD: shopping_store

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopping_store -d shopping_store"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - shopping-store-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:16-alpine
    container_name: order-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order -d order_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - order-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16-alpine
    container_name: payment-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    ports:
      - "5437:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U payment -d payment" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  delivery-db:
    image: postgres:16-alpine
    container_name: delivery-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery
    ports:
      - "5438:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U delivery -d delivery" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - delivery-db-data:/var/lib/postgresql/data


volumes:
  shopping-store-db-data:
  shopping-cart-db-data:
  warehouse-db-data:
  order-db-data:
  payment-db-data:
  delivery-db-data: