spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.serializer.AvroSerializer

      acks: all
      retries: 10

      properties:
        enable.idempotence: true
        linger.ms: 5
        batch.size: 32768
        compression.type: snappy
        request.timeout.ms: 30000
        delivery.timeout.ms: 120000