app:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.serializer.AvroSerializer

    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1