spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api/v1
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - PrefixPath=/api/v1
        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
          filters:
            - PrefixPath=/api/v1
        - id: shopping-cart-route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/shopping-cart

        - id: shopping-store-route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/shopping-store
            - name: Retry
              args:
                retries: 3
                statuses:
                  - NOT_FOUND
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms
                  factor: 2