spring:
  application:
    name: aggregator
  config:
    fail-fast: true
    retry:
      initial-interval: 2000
      multiplier: 1.5
      max-interval: 1000
      max-attempts: 20
    import: configserver:http://localhost:8888
