spring:
  application:
    name: warehouse
  datasource:
    url: ${WAREHOUSE_DB_URL:jdbc:postgresql://localhost:5435/warehouse}
    driver-class-name: org.postgresql.Driver
    username: ${WAREHOUSE_DB_USERNAME:warehouse}
    password: ${WAREHOUSE_DB_PASSWORD:warehouse}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
server:
  port: 0
